name: Mmdevs

on:
  pull_request:
    branches:
      - main

jobs:
  welcome_message:
    if: github.event.action == 'opened'

    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: Run welcome message
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.SUSEE_BOT_PAT_TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const issue_number = context.payload.pull_request.number;

            const comment_body = `\n🙏🙏🙏 Welcome from mmdevs! Thank you for creating a PR.\n\nThe validation process is running soon, please wait until it passes.`;

            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number,
              body: comment_body,
            });
