name: Mmdevs

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - edited
      - synchronize
      - ready_for_review

permissions:
  contents: read
  pull-requests: read
  actions: read

jobs:
  validate-config:
    name: Validate subdomain config
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        id: checkout_pr_head
        with:
          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
          token: ${{ secrets.SUSEE_BOT_PAT_TOKEN }}
        # source repository
      - uses: actions/checkout@v6
        id: checkout_source_repo
        with:
          repository: phothinmg/mmdevs
          path: mmdevs

      - name: Setup Node.js
        id: setup_node
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: npm
          cache-dependency-path: mmdevs/package-lock.json

      - name: Install dependencies
        id: install_dependencies
        run: npm ci
        working-directory: mmdevs

      - name: Build Source
        id: build_source
        run: npm run build
        working-directory: mmdevs

      - name: Check PR Body
        id: check_pr_body
        env:
          GITHUB_TOKEN: ${{ secrets.MMDEV_GH_REPO_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          node opt/prBody.mjs
        working-directory: mmdevs

      - name: Check PR User Location
        id: check_pr_user_location
        env:
          GITHUB_TOKEN: ${{ secrets.MMDEV_GH_REPO_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          node opt/user.mjs
        working-directory: mmdevs
